Create post UI
Tejas1510/Athavani pull request #134
Opened 2021-03-17 19:38 UTC by AmeyaJain-25

I have created a new UI for create post.
![Screenshot from 2021-03-18 00-46-38](https://user-images.githubusercontent.com/66305085/111525453-a72ad600-8783-11eb-9263-f90c55b68c4c.png)

I've made the UI looking good, attractive and with some descent CSS with matching color theme of the application.
The creator's name which was in an input tag was not looking good, so removed that and added the name tag for it.
Here's the form screenshot.
![Screenshot from 2021-03-18 01-02-01](https://user-images.githubusercontent.com/66305085/111527686-30dba300-8786-11eb-85e0-cb30e33e598c.png)

Also I have removed the regular upload choose a file button to the Upload Icon.
![Screenshot from 2021-03-18 00-46-26](https://user-images.githubusercontent.com/66305085/111526034-3df79280-8784-11eb-8bdd-af58e474a5ec.png)

2021-03-18 16:43 UTC, sanjay270899 commented
@AmeyaJain-25 Nice Work!

But maybe text color in white would look better. Try some different color combinations and send the screenshots. Rest is fine.

2021-03-18 18:45 UTC, AmeyaJain-25 commented
Here are some screenshots.
![Screenshot from 2021-03-19 00-04-36](https://user-images.githubusercontent.com/66305085/111680187-f9cdc600-8847-11eb-902d-334e07d418e1.png)
![Screenshot from 2021-03-19 00-01-56](https://user-images.githubusercontent.com/66305085/111680212-fe927a00-8847-11eb-99b5-cc69bf43f6a7.png)
![Screenshot from 2021-03-18 23-59-10](https://user-images.githubusercontent.com/66305085/111680248-094d0f00-8848-11eb-9323-938ed26cf5da.png)
![Screenshot from 2021-03-18 23-56-38](https://user-images.githubusercontent.com/66305085/111680268-0eaa5980-8848-11eb-8487-b5ad24ab5370.png)

2021-03-19 11:11 UTC, sanjay270899 commented
@AmeyaJain-25 `2nd` and `4th` are looking better. Choose one of them and then I will merge this PR.

2021-03-19 12:58 UTC, AmeyaJain-25 commented
I've made the second one and pushed the code.
Thanks @sanjay270899

2021-03-19 20:25 UTC, sanjay270899 requested changes

2021-03-19 20:25 UTC, sanjay270899 commented on client/src/components/Form/Form.js
> +            {/* <TextField
Please remove this if it is not in use.

2021-03-20 21:24 UTC, merged

2021-03-21 14:07 UTC, sanjay270899 commented
Fixes #125